### ISSUE TITLE
`LY: Print error (No such file or directory)` displayed during retrieving schema after connection established

### ISSUE THREAD

**Issue by brchiu** [CESNET/libnetconf2#176] opened 2019-10-16 01:50 UTC
I got the following error message `[ERR]: LY: Print error (No such file or directory)` when connecting `netopeer2-server` with `netopeer2-cli` on petalinux over QEMU.

Most of the time, this message happened after `channel_rcv_change_window:`.

Some debug information are added by me.

```
[INF]: LY: All data nodes and constraints resolved.
[INF]: LN: Schema "o-ran-externalio" was requested.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: NP: Session 1: thread 1 event new RPC.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: LN: Schema "o-ran-fan" was requested.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: NP: Session 1: thread 1 event new RPC.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: LN: Schema "o-ran-file-management" was requested.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[2019/10/16 01:34:47.590874, 2] channel_rcv_change_window:  Adding 640420 bytes to channel (43:43) (from 639573 bytes)
nc_write 754 : 2 No such file or directory
nc_write 740 : 2 No such file or directory
channel_write_common 1398 : 2 No such file or directory
lyxml_dump_text 1314 : 2 No such file or directory
nc_write 740 : 2 No such file or directory
channel_write_common 1398 : 2 No such file or directory
nc_write 740 : 2 No such file or directory
channel_write_common 1398 : 2 No such file or directory
xml_print_anydata 581 : 2 No such file or directory
[ERR]: LY: Print error (No such file or directory). line 629
[ERR]: LN: Session 1: failed to write reply.
[ERR]: LN: Session 1: SSH channel unexpected EOF.
[INF]: NP: Session 1: thread 4 event session terminated.
[INF]: SR: There are no subscribers for "ietf-netconf-notifications" notifications.
[INF]: NP: Generated new event (netconf-session-end).
```

**Comment by michalvasko** [comment] 2019-10-16 06:06
Hi,
so what exactly does the output mean? If they are lines, file names would help and also they will probably no longer match as I have just merged a pull request. But I have not seen such an error before.

Regards,
Michal

**Comment by brchiu** [comment] 2019-10-16 06:11
They are function name plus line number that I am trying to pin-point the place error occurred. without the debug messages, only the following ones I mentioned before, i.e. `LY: Print error (No such file or directory)` displayed.
```
[2019/10/16 01:34:47.590874, 2] channel_rcv_change_window:  Adding 640420 bytes to channel (43:43) (from 639573 bytes)
[ERR]: LY: Print error (No such file or directory).
[ERR]: LN: Session 1: failed to write reply.
```

**Comment by michalvasko** [comment] 2019-10-16 06:21
So the first error was caused by `ssh_channel_is_eof()` returning `1`? If so, maybe some *libssh* debugging output would help (`netopeer2-server -d -c SSH`).

Regards,
Michal

**Closed** 2022-08-18 12:55 UTC
