### ISSUE TITLE
rpc memory leak in this branch

### ISSUE THREAD

**Issue by yonghuhaige** [CESNET/libnetconf2#90] opened 2018-10-09 08:44 UTC
https://github.com/CESNET/libnetconf2/blob/9662233950fc16d91c2a84597296f9d42ce4fb8b/src/session_server.c#L1095

nc_ps_poll -> nc_server_recv_rpc_io
when parsing RPC failed,
ret = NC_PSPOLL_REPLY_ERROR | NC_PSPOLL_BAD_RPC,
rpc is not free

**Comment by michalvasko** [comment] 2018-10-11 07:45
Duplicate of #88.

**Closed by michalvasko** 2018-10-11 07:45 UTC
