### ISSUE TITLE
 ERR: Received an invalid message (Node "next-update-at" not found as a child of "edit-config" node.).

### ISSUE THREAD

**Issue by lorandt1** [CESNET/libnetconf2#473] opened 2024-03-27 09:35 UTC
[RPC-exchange.txt](https://github.com/CESNET/libnetconf2/files/14771157/RPC-exchange.txt)
Using 

l**ibnetconf2 3.0.8** and **libyang 2.1.148**:

1. send RPC with msg id 41: - edit-config
2. send RPC with msg id 42: - supervision-watchdog-reset
3. receive rpc-reply for msg id 41 
 -> 2024-03-26T15:30:23.706Z Err: [127.0.0.1] Session 1: Received an invalid message (Node "next-update-at" not found as a child of "edit-config" node.).
 
 Based on 
![image](https://github.com/CESNET/libnetconf2/assets/112163723/e983d46b-7892-4d1d-a3b0-aeb66a4a46e0)
I think it is certainly normal to happen

Old **libnetconf2 2.0.24 and libyang 2.0.112** could handle this case and reply with:

 ERR(session, "Received a <rpc-reply> with an unexpected message-id %" PRIu64 " (expected %" PRIu64 ").",
    cur_msgid, msgid);
return NC_MSG_REPLY_ERR_MSGID;

Then the client could still receive the reply of rpc with message id 41

RPC exchanges attached in RPC-exchange.txt.
Thank you!

**Comment by michalvasko** [comment] 2024-03-27 14:49
Should be fixed.

**Comment by lorandt1** [comment] 2024-03-28 12:08
Thanks again! May I ask when is planned a new libnetconf2 release ?

**Comment by michalvasko** [comment] 2024-03-28 12:14
As soon as the current version becomes a bit more stable, there are still changes being made (mostly in *sysrepo*). A couple of weeks at most, I hope.

**Comment by lorandt1** [comment] 2024-04-02 10:55
After I took the changes from devel branch (1.patch contains the differences between the initial fix I received and the one from devel branch added via commit  b25c56f) I faced a crash that occurs after a rpc-error for following rpc requst: `<rpc
	xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="1">
	<get
		xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
		<filter type="xpath"
			xmlns:yanglib="urn:ietf:params:xml:ns:yang:ietf-yang-librar
y" select="/yanglib:*"/>
		</get>
	</rpc>`
	
[logsBeforeCrash.txt](https://github.com/CESNET/libnetconf2/files/14835471/logsBeforeCrash.txt)

**Comment by michalvasko** [comment] 2024-04-02 11:30
I have tested on the current `devel`, CLI output:
```
> get --filter-xpath=/yanglib:*
ly ERROR: Failed to resolve prefix "yanglib".
ERROR
        type:     application
        tag:      operation-failed
        severity: error
        message:  Storing value failed.
```
and the server errors, which are better:
```
[ERR]: LY: Unexpected XPath expression end. (path "/ietf-netconf:get/filter/@ietf-netconf:select")
[ERR]: LY: Storing value failed. (path "/ietf-netconf:get/filter/@ietf-netconf:select")
```
so I cannot reproduce this.

**Closed** 2024-04-05 07:07 UTC
Labels: is:bug, status:completed

**Comment by lorandt1** [comment] 2024-04-05 07:15
The crash didn't appear for me either using the current devel.
