### ISSUE TITLE
Timeout happening for libnetconf2 using ssh client request

### ISSUE THREAD

**Issue by vishalearnz** [CESNET/libnetconf2#209] opened 2020-02-12 11:38 UTC
Hi Michal,

I am trying to do an ssh login request from command line by specifying the port and subsystem on which netconf is running .
Following is the request
ssh nm@10.220.30.49 -p 830 -s netconf

It gets connected to the libnetconf2 server but after few seconds it gets disconnected. 
Other than ssh if I use other means to login (like mgsoft and odl) , this disconnect is not seen.

Also after the ssh connection gets established I can send hello message and get request comfortably but whenever there is an idle time for nearly 25-30 secs the server disconnects

When I enabled the verbose logs of libnetconf2 , I can find the following logs to be printed
"{LibNetConfOriginator.cpp:286} LIBNETCONF : Session 1: inactive read timeout elapsed."
When I checked in the libnetconf2 code , I can find that nc_read gets called and if it has nothing to read , returns -1 and timeout happens .

But I fail to understand why this behavior is not seen in either Mgsoft of ODL , as I cant see any other request from Mgsoft or ODL gets sent to the libnetconf2 server other than login where capabilities are exchanged and hello is recieved.

Can you pl tell me what should I change so that simulate the similar behavior using ssh command(mentioned above) as what I can see using Mgsoft and ODL , where it doesn't gets disconnected indefinitely.

Note: I am not using Netopeer/Sysrepo server.
 
Thanks & Regards,
Vishal

**Comment by jktjkt** [comment] 2020-02-12 11:40
Check https://github.com/CESNET/libnetconf2/issues/192 and [the fix upstream in libssh](https://bugs.libssh.org/rLIBSSH022409e99c9f6d6f1e540da5c2fa925b72998974) if it's relevant for you.

**Comment by michalvasko** [comment] 2020-02-12 12:09
@jktjkt This is an actual *libnetconf2* timeout (the message is clear), it should not have anything to do with *libssh*.

@vishalearnz This *libnetconf2* timeout is for cases when the client sends only part of a message and never the rest of it, as a defense against DoS. So that is what is happening in your case, you are sending the beginning of the next NETCONF message without the rest of it. Since NETCONF is quite strict regarding the [expected message format](https://tools.ietf.org/html/rfc6242#section-4.3) (I assume you are using NETCONF 1.0 encoding), you should always use a NETCONF client, then you will have no problems.

Specifically, I would say you are always sending a newline at the end of every message, it is not expected. *libnetconf2* processes the first message and then reads the newline. It can only assume that to be the beginning of the next message, but it is not in your case.

Regards,
Michal

**Comment by vishalearnz** [comment] 2020-02-14 11:00
I tried putting the message format as mentioned above but still it doesn't work . It disconnects .  I am not sure how the ssh is sending the packets so there might be discrepancies in forming them as to what I am sending from command line. Still if you have any input pl let me know . Following is the hello message I am sending 

<hello xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <capabilities>
    <capability>urn:ietf:params:netconf:base:1.0</capability>
  </capabilities>
</hello>
]]>]]>

and the get request:

<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="1">
<get >
    <filter type="subtree">
        <users xmlns="com:infinera:security:user"/>    			
    </filter>
</get>
</rpc>
]]>]]>

Note : The response I receive at the client side doesnot contain a new line

**Comment by michalvasko** [comment] 2020-02-14 11:39
Hi,
the problem is that `ssh(1)` actually sends
 ```
urn:ietf:params:netconf:base:1.0 ]]>]]>\n
```
as far as I know. And it is not possible to get rid of the newline. After I learned this, I have stopped using `ssh` for NETCONF.

Regards,
Michal

**Comment by kramarz89** [comment] 2020-04-01 14:27
Hi,

Could it be that libnetconf2 sees this newline and thinks the message did not end yet? Cause I think that is what is happening, because when I disabled inactive timeout (by introducing if cases for when the timeout is 0 - do nothing) then it's the *active* timeout that is elapsing. and causing a session drop/reconnect

**Comment by michalvasko** [comment] 2020-04-02 09:16
Hi,
you see, there is nothing much I can about this. NETCONF has exact specification as to what should every message contain and that is all there is to it. *libnetconf2* cannot ignore newlines because "ssh utility always sends it". You are supposed to use a NETCONF client, then you will have no problems.

As for you using *libssh* 0.9.3, it should not be possible to compile with it because there are some critical bugs. Unless you have not taken the official release but current libssh `master`, in which case it should be fine and the bugs should be fixed.

Regards,
Michal

**Comment by kramarz89** [comment] 2020-04-02 10:42
Hi Michal,

The thing is, I am using netopeer2-cli. And after call home from the server, if I do not act upon anything, then the **inactive** timeout happens. If i disable it as mentioned, then the **active** timeout happens.

**Comment by michalvasko** [comment] 2020-04-02 13:00
Like I said, it should not even be possible to compile *libnetconf2* with *libssh* 0.9.3. Good that it works now.

**Closed by michalvasko** 2020-04-02 13:00 UTC

**Comment by RogerYaozhenyu** [comment] 2020-05-12 02:59
hi,michal, i run into the same problem . but  if i compile old libnetconf2 version with libssh 0.9.3. it works.  when i upgreade libnetconf2  to the lastest version . it turn out this "time out" issue.

**Comment by michalvasko** [comment] 2020-05-12 06:18
Hi,
are you using a proper NETCONF client or `ssh(1)`? What *libssh* version are you using?

Regards,
Michal

**Comment by RogerYaozhenyu** [comment] 2020-05-12 07:30
hi, michal,  when we upgreade libssh to 0.9.4 and merge the the lastest src/channels.c which fixed at 7 days ago. this issue is gone

**Comment by michalvasko** [comment] 2020-05-12 07:41
Hi,
yes, that makes sense.

Regards,
Michal
