### ISSUE TITLE
libnetconf2 cross compile: camke  failed

### ISSUE THREAD

**Issue by Arvliu** [CESNET/libnetconf2#174] opened 2019-10-12 00:51 UTC
cd libnetconf2
mkdir build; cd build;
cmake .. -DCMAKE_C_COMPILER=arm-arago-linux-gnueabi-gcc 
Looking for pthread.h - not found
Cmake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArfs.cmake:137(message):
Could NOT find Threads(missing:Threads_FOUND)

Has anyone ever had a similar problem?

**Comment by michalvasko** [comment] 2019-10-12 06:50
Duplicate of #139

**Closed by michalvasko** 2019-10-12 06:50 UTC
